//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string day {
            get {
                return ((string)(this["day"]));
            }
            set {
                this["day"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string month {
            get {
                return ((string)(this["month"]));
            }
            set {
                this["month"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string year {
            get {
                return ((string)(this["year"]));
            }
            set {
                this["year"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkeda {
            get {
                return ((bool)(this["checkeda"]));
            }
            set {
                this["checkeda"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=C:\\Users\\Denis\\Documents\\Databases\\D" +
            "atabase4\\BS.mdf;Integrated Security=True;Connect Timeout=30")]
        public string BSConnectionString {
            get {
                return ((string)(this["BSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\Denis\\Documents\\Databases\\" +
            "Database4\\BS.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string BSConnectionString1 {
            get {
                return ((string)(this["BSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.Forms.FormWindowState Maximised {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["Maximised"]));
            }
            set {
                this["Maximised"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\ogden\\Documents\\Dither Tec" +
            "hnologies\\KCDSACCO\\BS.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string BSConnectionString2 {
            get {
                return ((string)(this["BSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HotTrack")]
        public global::System.Drawing.Color usercolor {
            get {
                return ((global::System.Drawing.Color)(this["usercolor"]));
            }
            set {
                this["usercolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2007Blue")]
        public global::DevComponents.DotNetBar.eStyle userstyle {
            get {
                return ((global::DevComponents.DotNetBar.eStyle)(this["userstyle"]));
            }
            set {
                this["userstyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FlatRate")]
        public string intresttype {
            get {
                return ((string)(this["intresttype"]));
            }
            set {
                this["intresttype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monthly")]
        public string loantype {
            get {
                return ((string)(this["loantype"]));
            }
            set {
                this["loantype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frontendprinter {
            get {
                return ((string)(this["frontendprinter"]));
            }
            set {
                this["frontendprinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barcodeprinter {
            get {
                return ((string)(this["barcodeprinter"]));
            }
            set {
                this["barcodeprinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string monthlycharge {
            get {
                return ((string)(this["monthlycharge"]));
            }
            set {
                this["monthlycharge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string smsallow {
            get {
                return ((string)(this["smsallow"]));
            }
            set {
                this["smsallow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smsusername {
            get {
                return ((string)(this["smsusername"]));
            }
            set {
                this["smsusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smspassword {
            get {
                return ((string)(this["smspassword"]));
            }
            set {
                this["smspassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\ogden\\Documents\\Dither Tec" +
            "hnologies\\SACCO\\BS.mdf\";Integrated Security=True;Connect Timeout=30")]
        public string BSConnectionString3 {
            get {
                return ((string)(this["BSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHPU")]
        public string companycode {
            get {
                return ((string)(this["companycode"]));
            }
            set {
                this["companycode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string sharesinclude {
            get {
                return ((string)(this["sharesinclude"]));
            }
            set {
                this["sharesinclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string compulsoryprocessing {
            get {
                return ((string)(this["compulsoryprocessing"]));
            }
            set {
                this["compulsoryprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string compulsoryinsurance {
            get {
                return ((string)(this["compulsoryinsurance"]));
            }
            set {
                this["compulsoryinsurance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Percentage")]
        public string Loanprocessingtype {
            get {
                return ((string)(this["Loanprocessingtype"]));
            }
            set {
                this["Loanprocessingtype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public string autoloanfines {
            get {
                return ((string)(this["autoloanfines"]));
            }
            set {
                this["autoloanfines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int autoloandays {
            get {
                return ((int)(this["autoloandays"]));
            }
            set {
                this["autoloandays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Percentage")]
        public string Loaninsurancetype {
            get {
                return ((string)(this["Loaninsurancetype"]));
            }
            set {
                this["Loaninsurancetype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Percentage")]
        public string loanmultipletype {
            get {
                return ((string)(this["loanmultipletype"]));
            }
            set {
                this["loanmultipletype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string userdb {
            get {
                return ((string)(this["userdb"]));
            }
            set {
                this["userdb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string usercon {
            get {
                return ((string)(this["usercon"]));
            }
            set {
                this["usercon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string connectionsuccess {
            get {
                return ((string)(this["connectionsuccess"]));
            }
            set {
                this["connectionsuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string realcon {
            get {
                return ((string)(this["realcon"]));
            }
            set {
                this["realcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string servernam {
            get {
                return ((string)(this["servernam"]));
            }
            set {
                this["servernam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jesus@lord1")]
        public string serverpass {
            get {
                return ((string)(this["serverpass"]));
            }
            set {
                this["serverpass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string conserver {
            get {
                return ((string)(this["conserver"]));
            }
            set {
                this["conserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("you")]
        public string readcon {
            get {
                return ((string)(this["readcon"]));
            }
            set {
                this["readcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ribbonTabItem2")]
        public string currentselection {
            get {
                return ((string)(this["currentselection"]));
            }
            set {
                this["currentselection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yes")]
        public string receiptlogo {
            get {
                return ((string)(this["receiptlogo"]));
            }
            set {
                this["receiptlogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yes")]
        public string reportlogo {
            get {
                return ((string)(this["reportlogo"]));
            }
            set {
                this["reportlogo"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DENIS\\SQLEXPRESS;Initial Catalog=Sacco;Persist Security Info=True;Use" +
            "r ID=sa;Password=jesus@lord1")]
        public string SaccoConnectionString {
            get {
                return ((string)(this["SaccoConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Manual")]
        public string autotransfer {
            get {
                return ((string)(this["autotransfer"]));
            }
            set {
                this["autotransfer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int autotransferdays {
            get {
                return ((int)(this["autotransferdays"]));
            }
            set {
                this["autotransferdays"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DENIS\\SQLEXPRESS;Initial Catalog=Lending;Persist Security Info=True;U" +
            "ser ID=sa;Password=jesus@lord1")]
        public string LendingConnectionString {
            get {
                return ((string)(this["LendingConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string ThreadsAuto {
            get {
                return ((string)(this["ThreadsAuto"]));
            }
            set {
                this["ThreadsAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POS")]
        public string receipttype {
            get {
                return ((string)(this["receipttype"]));
            }
            set {
                this["receipttype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("showdialog")]
        public string PrintOptions {
            get {
                return ((string)(this["PrintOptions"]));
            }
            set {
                this["PrintOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dither Tech")]
        public string Smscode {
            get {
                return ((string)(this["Smscode"]));
            }
            set {
                this["Smscode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+256787045644")]
        public string phoneinquiry {
            get {
                return ((string)(this["phoneinquiry"]));
            }
            set {
                this["phoneinquiry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string RescheduleAmount {
            get {
                return ((string)(this["RescheduleAmount"]));
            }
            set {
                this["RescheduleAmount"] = value;
            }
        }
    }
}
